BEGIN TRANSACTION;
CREATE TRIGGER IF NOT EXISTS readonly_md5_insert
BEFORE INSERT ON md5
FOR EACH ROW
BEGIN
    SELECT RAISE(IGNORE);
END;
CREATE TRIGGER IF NOT EXISTS readonly_md5_update
BEFORE UPDATE ON md5
FOR EACH ROW
BEGIN
    SELECT RAISE(IGNORE);
END;
CREATE TRIGGER IF NOT EXISTS readonly_md5_delete
BEFORE DELETE ON md5
FOR EACH ROW
BEGIN
    SELECT RAISE(IGNORE);
END;
CREATE TRIGGER IF NOT EXISTS readonly_sha1_insert
BEFORE INSERT ON sha1
FOR EACH ROW
BEGIN
    SELECT RAISE(IGNORE);
END;
CREATE TRIGGER IF NOT EXISTS readonly_sha1_update
BEFORE UPDATE ON sha1
FOR EACH ROW
BEGIN
    SELECT RAISE(IGNORE);
END;
CREATE TRIGGER IF NOT EXISTS readonly_sha1_delete
BEFORE DELETE ON sha1
FOR EACH ROW
BEGIN
    SELECT RAISE(IGNORE);
END;
CREATE TRIGGER IF NOT EXISTS readonly_sha256_insert
BEFORE INSERT ON sha256
FOR EACH ROW
BEGIN
    SELECT RAISE(IGNORE);
END;
CREATE TRIGGER IF NOT EXISTS readonly_sha256_update
BEFORE UPDATE ON sha256
FOR EACH ROW
BEGIN
    SELECT RAISE(IGNORE);
END;
CREATE TRIGGER IF NOT EXISTS readonly_sha256_delete
BEFORE DELETE ON sha256
FOR EACH ROW
BEGIN
    SELECT RAISE(IGNORE);
END;
COMMIT;
PRAGMA optimize;
VACUUM;
PRAGMA quick_check;